# Generated by Django 2.1.1 on 2018-09-18 03:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('slug', models.SlugField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='page',
        ),
        migrations.AddField(
            model_name='photo',
            name='albums',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogAPI.Album'),
            preserve_default=False,
        ),
    ]
