# Generated by Django 2.1.1 on 2018-09-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0002_auto_20180925_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='text',
        ),
        migrations.AddField(
            model_name='album',
            name='summary',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
