# Generated by Django 2.1.1 on 2018-09-18 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0002_auto_20180917_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='albums',
        ),
        migrations.AddField(
            model_name='album',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogAPI.Photo'),
            preserve_default=False,
        ),
    ]
