# Generated by Django 2.1.1 on 2018-09-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='header',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
