# Generated by Django 2.1.1 on 2018-09-18 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0003_auto_20180918_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogAPI.Album'),
            preserve_default=False,
        ),
    ]
