# Generated by Django 2.1.1 on 2018-09-18 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0005_photo_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='blogAPI.Album'),
        ),
    ]
