version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
    volumes: 
      - ./postgres_data:/var/lib/posgresql/data
    env_file: PersonalBlogAPI/settings/.env
    ports:
      - "5432"
  web:
    build: .
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000 --settings=PersonalBlogAPI.settings.docker"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: PersonalBlogAPI/settings/.env
    depends_on:
      - db