version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
    volumes: 
      - ./postgres_data:/var/lib/posgresql/data
    env_file: .env
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 /app.manage.py makemigrations
    command: python3 /app/manage.py migrate
    command: python3 /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db