version: "3"
services:
  django:
    container_name: personalblogapi_django
    build:
      context: .
      dockerfile: Dockerfile
    image: personalblogapi
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"